### ISSUE TITLE
Analog Video Elevated Blacks/Green

### ISSUE THREAD

**Issue by leckel1996** [nukeykt/Nuked-MD#27]
When using the core over analog video the blacks are elevated and there is a green tint. This is not present on hdmi output.

**Comment by ogamespec** [comment]
Are you sure it's for a software emulator?

**Comment by leckel1996** [comment]
I’m not sure I understand your question.

**Comment by nukeykt** [comment]
pls do not bug us about mister & other fpga board related stuff

**Comment by leckel1996** [comment]
My apologies. I definitely meant to submit this elsewhere.
