### ISSUE TITLE
arbiter.c ARB_ClockVCLKDivider redundand code

### ISSUE THREAD

**Issue by ogamespec** [nukeykt/Nuked-MD#5]
```
chip->w266 = chip->w289 && chip->w356 && chip->w356;
```

w356 two times :wtf:

**Comment by nukeykt** [comment]
![image](https://github.com/nukeykt/Nuked-MD/assets/15833655/acf0255b-39f1-4020-9355-4f76ac9a7c81)
w356 connects to 2 inputs of w266 cell (and3)

**Comment by ogamespec** [comment]
Weirdos
